### ISSUE TITLE
Dependency w3m and segmentation fault whenever I execute it

### ISSUE THREAD

**Issue by vicentebolea** [Jarkore/Feednix#15]
Hi, I got the following error:
     
      vicente at vicente-ubuntu in ~ $ 
      → feednix  
      sh: 1: w3m: not found
      sh: 1: w3m: not found
      sh: 1: w3m: not found
      Segmentation fault (core dumped)

After installing w3m I get the following line whenever I run it:
      
       Segmentation fault (core dumped)

Even I remove the config files in .config/feednix, it might work for few seconds and after setting my account I get the same error.
 
       Core was generated by `feednix'.
       Program terminated with signal 11, Segmentation fault. 
       #0  0x00007f33638c2211 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
       (gdb) bt
        #0  0x00007f33638c2211 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
        #1  0x000000000041421f in ?? ()
        #2  0x0000000000415793 in ?? ()
        #3  0x00000000004051ba in ?? ()
        #4  0x00007f336378076d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
        #5  0x00000000004056a1 in ?? () 
        #6  0x00007fff2fdd28e8 in ?? ()
        #7  0x000000000000001c in ?? ()
        #8  0x0000000000000001 in ?? ()
        #9  0x00007fff2fdd4416 in ?? ()
        #10 0x0000000000000000 in ?? ()
        
I am using the last version from the master branch in ubuntu 12.04

**Comment by Jarkore** [comment]
I have not been able to replicate this bug but I have attempted a fix. At the very least it should handle w3m's absence if this is the case, incorrect path (which is unlikely but still), and some other error handling. You can pull the latest changes and see if the fix works and/or if there any changes.

Thanks
