### ISSUE TITLE
Issue installing under Mint 17

### ISSUE THREAD

**Issue by darkbls** [Jarkore/Feednix#18]
I have installed the cpp/c json dev libs in the system, but the result is the same.

What could I be missing?

    lnaia@darkbluesea-loc ~/apps/Feednix $ ./configure
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for style of include used by make... GNU
    checking dependency style of g++... gcc3
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for curl_easy_init in -lcurl... yes
    checking for _ZNK4Json5Value4sizeEv in -ljsoncpp... yes
    checking for free_item in -lmenu... yes
    checking for initscr in -lncurses... yes
    checking for new_panel in -lpanel... yes
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking termios.h usability... yes
    checking termios.h presence... yes
    checking for termios.h... yes
    checking for unistd.h... (cached) yes
    checking for stdbool.h that conforms to C99... yes
    checking for _Bool... yes
    checking for size_t... yes
    checking for atexit... yes
    checking for strdup... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/Makefile
    config.status: creating config.h
    config.status: config.h is unchanged
    config.status: executing depfiles commands
    lnaia@darkbluesea-loc ~/apps/Feednix $ make
    make  all-recursive
    make[1]: Entering directory `/home/lnaia/apps/Feednix'
    Making all in src
    make[2]: Entering directory `/home/lnaia/apps/Feednix/src'
    g++ -DHAVE_CONFIG_H -I. -I..  -DDEBUG -std=c++11 -Wall    -g -O2 -MT feednix-main.o -MD -MP -MF .deps/feednix-main.Tpo -c -o feednix-main.o `test -f 'main.cpp' || echo './'`main.cpp
    main.cpp: In function ‘void atExitFunction()’:
    main.cpp:16:175: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(std::string("find " + std::string(HOME_PATH) + "/.config/feednix -type f -not -name \'config.json\' -and -not -name \'log.txt\' -delete 2> /dev/null").c_str());
                                                                                                                                                                                   ^
    main.cpp:17:73: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(std::string("rm -R " + TMPDIR + " 2> /dev/null").c_str());
                                                                             ^
    main.cpp: In function ‘void sighandler(int)’:
    main.cpp:23:175: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system(std::string("find " + std::string(HOME_PATH) + "/.config/feednix -type f -not -name \'config.json\' -and -not -name \'log.txt\' -delete 2> /dev/null").c_str());
                                                                                                                                                                                   ^
    main.cpp: In function ‘int main(int, char**)’:
    main.cpp:42:116: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                     system(std::string("mkdir -p " + std::string(HOME_PATH) + "/.config/feednix &> /dev/null").c_str());
                                                                                                                        ^
    main.cpp:43:126: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                     system(std::string("cp /etc/xdg/feednix/config.json " + std::string(HOME_PATH) + "/.config/feednix").c_str());
                                                                                                                                  ^
    main.cpp:44:116: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
                     system(std::string("chmod 600 " + std::string(HOME_PATH) + "/.config/feednix/config.json").c_str());
                                                                                                                        ^
    mv -f .deps/feednix-main.Tpo .deps/feednix-main.Po
    g++ -DHAVE_CONFIG_H -I. -I..  -DDEBUG -std=c++11 -Wall    -g -O2 -MT feednix-FeedlyProvider.o -MD -MP -MF .deps/feednix-FeedlyProvider.Tpo -c -o feednix-FeedlyProvider.o `test -f 'FeedlyProvider.cpp' || echo './'`FeedlyProvider.cpp
    FeedlyProvider.cpp:5:25: fatal error: json/writer.h: No such file or directory
     #include <json/writer.h>
                             ^
    compilation terminated.
    make[2]: *** [feednix-FeedlyProvider.o] Error 1
    make[2]: Leaving directory `/home/lnaia/apps/Feednix/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/lnaia/apps/Feednix'
    make: *** [all] Error 2
    lnaia@darkbluesea-loc ~/apps/Feednix $

**Comment by Jarkore** [comment]
The issue is that jsoncpp's files are in different paths in different distros. You can try adding -I=/usr/include/jsoncpp to the file or try the Ubuntu stable branch and see if this corrects the issue.
