### ISSUE TITLE
Feednix 

### ISSUE THREAD

**Issue by frtorres** [Jarkore/Feednix#20]
I am a regular Android feedly user, installed and compiled feedix according to:

xmodulo.com/feedly-rss-feed-command-line-linux.html

run for the first time and I was browsing just tto explore the app. After I tried to run again I got this:

feednix: src/lib_json/json_value.cpp:1073: Json::Value& Json::Value::operator[](Json::Value::ArrayIndex): Assertion `type_ == nullValue || type_ == arrayValue' failed.
                                             Aborted
~/.config/feednix/log.txt: reports only: 
ERROR: Curl Request Failed
 HTTP Response Code: 400
4 times... nothing special.

Please advice.

**Comment by Jarkore** [comment]
With what system are your running Feednix?

**Comment by frtorres** [comment]
Debian Jessie - running Linux 3.18.0-9-generic x86_64 [ Kanotix DISTRO Spitfire 20140426-16:53 ]
CPU Info        Quad Intel Core i7-4600U @ clocked at Min:2878.664Mhz Max:2990.777Mhz
Videocard       Intel Haswell-ULT Integrated Graphics Controller  X.Org 1.16.2.901  [ 1366x768 ]
Memory 3290.8/7890.3MB | HDD Size 256GB (67%used) | Client Shell | Infobash v2.67.2

**Comment by Jarkore** [comment]
Could you please confirm which version of jsoncpp you have installed?

**Comment by frtorres** [comment]
ii  libjsoncpp-dev                                    0.6.0~rc2-3.1
ii  libjsoncpp0                                       0.6.0~rc2-3.1

**Comment by Jarkore** [comment]
Could you please delete your config file for feednix. Retrive the tokens again and try a few more times?

The 400 error means that feedly recieved invalid json when sending requests so I am trying to see if its an issue with jsoncpp versions or if it is an issue with the tokens.

**Comment by frtorres** [comment]
1) May I reuse the original token? or request for a new one?
2) Btw, when I used feednix for the first time worked ok with my current rss several time. I did what You say deleting config file and recompiling, same bad result. But I did not request for new tokens.

Please advice

**Comment by Jarkore** [comment]
Yes you can reuse your tokens. Another thing that you can try is deleting anything in /tmp folder that has temp.XXXXX where XXXXX is any random string.

I will be honest with you I am not 100% sure of what is going on. I suspect the culprit is jsoncpp since the 400 error refers to invalid json. Do you have anything in your feeds in the lines of empty categories, feeds with UTF-8 characters?

**Comment by frtorres** [comment]
Ok.
1) there were not files on /tmp as you described.
2) rm ~/.config/feednix/config.json
3) reuse initial tokens.
regarding your questions:
4) Do you have anything in your feeds in the lines of empty categories, 
A/  NO,
5)feeds with UTF-8 characters?
A/  Maybe I have feeds in english and spanish mainly and my default locales are US  UTF-8

After #3. I run again feednix and it was OK. It has been at least working without crashing.
I will be testing more,. Because I have 7308 feeds now.... I feel it slow updating the categories but it is working by now and that is the important point now...

I will let you know if this issue repeat / new one.  

Thanks for your help.

Francisco
