### ISSUE TITLE
Feednix ARM

### ISSUE THREAD

**Issue by maauso** [Jarkore/Feednix#21]
Probably do you know, with arm systems we have this error.
cc1plus: error: unrecognized command line option ‘-std=c++11’

I test it with:
Linux raspbian 3.12.35+ 
gcc (Debian 4.6.3-14+rpi1) 4.6.3

**Comment by Jarkore** [comment]
Debian has a slow release cycle which means that your gcc is not up to the newest version and thus cannot compile C++11 standard code. If you wish you can follow these instructions to update your gcc on debian:

https://solarianprogrammer.com/2015/01/13/raspberry-pi-raspbian-install-gcc-compile-cpp-14-programs/
