### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by noilhan** [Jarkore/Feednix#22]
Hi, when launching feednix and reading some articles, or when refreshing, I get a core dumped.
It seems that the problem comes from a null pointer reference in CursesProvider.cpp.

Output from gdb:

(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/i386/i686/multiarch/strlen-sse2.S:62
#1  0x08058799 in length (__s=0x0) at /usr/include/c++/4.9/bits/char_traits.h:263
#2  assign (__s=0x0, this=0x95af3d0) at /usr/include/c++/4.9/bits/basic_string.h:1149
#3  operator= (__s=0x0, this=0x95af3d0) at /usr/include/c++/4.9/bits/basic_string.h:563
#4  CursesProvider::createPostsMenu (this=0x95af230) at CursesProvider.cpp:390
#5  0x08059082 in CursesProvider::init (this=0x95af230) at CursesProvider.cpp:91
#6  0x0804bca5 in main (argc=1, argv=0xbfcc2e74) at main.cpp:83
(gdb) frame 4
#4  CursesProvider::createPostsMenu (this=0x95af230) at CursesProvider.cpp:390
390                     lastEntryRead = item_description(postsItems[0]);
(gdb) list
385                             postsItems[i] = new_item((it->title).c_str(), (it->id).c_str());
386                             i++;
387                     }
388
389                     postsMenu = new_menu((ITEM **)postsItems);
390                     lastEntryRead = item_description(postsItems[0]);
391             }
392             else{
393                     postsMenu = new_menu(NULL);
394                     currentCategoryRead = true;
(gdb) print postsItems
$1 = (ITEM **) 0x965ee38
(gdb) print postsItems[0]
$2 = (ITEM *) 0x0

system: ubuntu 14.10, feednix just compiled from git repo, 

  Fabrice

**Comment by Jarkore** [comment]
Do you have feeds that use UTF-8?

**Comment by noilhan** [comment]
Yes. It seems that setting LC_CTYPE to "C" in a non-UTF-8 terminal "solves" the problem (at least no core dumped after a few screens of items). Unfortunately, this way makes also the reading quite difficult for UTF-8 characters.

**Comment by Jarkore** [comment]
If that is the case then did you make sure you installed and built with libncursesw instead of libncurses?

**Comment by noilhan** [comment]
Yes, it is linked with libncursesw.so.5.

I do not manage to get core dumps any longer (on my phone), I will make a more in-depth check tonight with a full-fledged terminal. 

It was maybe a peculiar entry that is now read.

**Comment by noilhan** [comment]
No core dump any longer, whatever the terminal or the LC_CTYPE setting is.
