### ISSUE TITLE
Cannot open URLs on Mac OS

### ISSUE THREAD

**Issue by sdabet** [Jarkore/Feednix#25]
URL opening doesn't seem to work on Mac OS:
* Initial authentication page doesn't load
* Nothing happens when hitting "o" to open an item

**Comment by Jarkore** [comment]
Feednix uses xdg to open links. I am not sure if Mac uses this or not but from past issues it seems that it does. Try to see if xdg has a default set for html links.

**Comment by nx357** [comment]
@Jarkore : After installing xdg-utils and w3m under MacPorts I do not have any preview of each post like your captures (see attachment and green arrow). Hitting "o" does nothing. Only the "O" input opens the link in safari.

How can I get those previews under w3m ?

Cheers
