### ISSUE TITLE
Can't open article on Feeding

### ISSUE THREAD

**Issue by cyberkurumin** [Jarkore/Feednix#29]
Hello all;

Your project seems just amazing and I'd really like to used as my rss reader.

The problem I have is that I'm on a mac on yosemite, and the install is not so smooth. But once I've installed, solving some issues using the closed issues posts, I can start and see the Categories and the RSS articles. But I can make no action.

When over an article and I press entre key, nothing happens. I can't preview the resume of the article.

Has anyone faced the same problem on a mac? Do I have to install something else? Maybe we could make a list of the dependencies one must install using homebrew in order to install and use Feednix.

Thank you for proposing a so nice project and keep it up guys!!!

**Comment by Jarkore** [comment]
The enter key doesn't do anything with the posts. If you want to preview it with w3m press o
