### ISSUE TITLE
Mac OS X building

### ISSUE THREAD

**Issue by jrcii** [Jarkore/Feednix#34]
I've been trying to build this on my Mac OS X 10.10. I got past the automake and json/json.h problems then have hit this roadblock when running make: http://paste.openstack.org/raw/249033/

I'm not really a systems programmer so not sure where to look to solve this. Any ideas / static binary links? :)

**Comment by Jarkore** [comment]
Please ensure that you installed jsoncpp. You can reference this past ticket to help you out.

https://github.com/Jarkore/Feednix/issues/16#issuecomment-75181825
