### ISSUE TITLE
Feednix wont start on Ubuntu

### ISSUE THREAD

**Issue by kernelfreak** [Jarkore/Feednix#36]
Hello,

I just installed Feednix on Ubuntu by following the guide. Unfortunately, it is not starting the feednix even after the make and make install is successful. Here is the error I get when I start 

akshay@akshay-desktop:~$ feednix
cp: cannot stat ‘/etc/xdg/feednix/config.json’: No such file or directory
chmod: cannot access ‘/home/akshay/.config/feednix/config.json’: No such file or directory
akshay@akshay-desktop:~$ 

And here is the screenshot of installation. So, what is wrong? Thank you.  
![screenshot from 2015-08-19 16 59 54](https://cloud.githubusercontent.com/assets/9052620/9359930/c15ae538-4693-11e5-8926-8bd324532eff.png)

**Comment by bhcopeland** [comment]
you need to create the config.json file....

Just copy it from the git repo

**Comment by kernelfreak** [comment]
Should I paste the config.json file manually?

**Comment by bhcopeland** [comment]
Yeah. That's what I did.

**Comment by kernelfreak** [comment]
Ok, Well, the feednix folder was also not created in /etc/xdg. Can you update your code/script to create the folder and copy the file as well. I was forced to create an issue as I couldn't find any help on net. Thank you for the nice app, its good. :+1:
